name: burstccn
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - numpy=1.22.3
  - pip=22.1.2
  - python=3.10.4
  - pytorch=1.12.0
  - torchvision=0.13.0
  - tqdm=4.64.0
  - pip:
    - wandb==0.12.21